### PR TITLE
Custom placeholder texts

### PR DESCRIPTION
**Pull request by beepsoft**
Hi Marco,

This is our proposal to extend the input descriptor of Profiles with a `placeholder` field, so that one can define custom, more semantic prompt in place of the default `Add text`.

See the `profile-with-constraints.json` Profile and its `Text field with no constraint` as an example in the develop app.

It is backward compatible and requires minimal code change. What do you think?

### CODE REVIEW

**Comment by marcolarosa** [comment]
The change looks ok but I don't understand the use case.

**Comment by beepsoft** [comment]
Such placeholders are used in Dataverse and we would like to have the same user experience in Describo as well:

image

**Comment by marcolarosa** [comment]
ok - will check it out Monday but it makes sense. Thanks for the explanation!

**Comment by marcolarosa** [comment]
0.80.0 built and published with this change

**Pull request merged**
